name: Lint

on:
  pull_request:

env:
  NODE_VERSION: "lts/*"
  PNPM_VERSION: 10

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm i

      - name: Code Linting
        run: pnpm lint
